Graded on 09-07 18:35:11
Grade: N/A%
Submission was 0 hours late.
Feedback: An error occured while grading your homework.. Traceback (most recent call last):
  File "/home/jack/Documents/Clones/sefa_classroom/combinedSystem/functions/gradeProcess.py", line 65, in startGradingProcess
    obj = interface.grade_submission(clonePath, profPath, int(hoursLate))
  File "/home/jack/Documents/Clones/sefa_classroom/combinedSystem/functions/GradingInterface/interface.py", line 277, in grade_submission
    points, user_feedback, testcases_dict = grade(user_submission.submission_folder_path, weights)  # grades submission and gets point values
  File "/home/jack/Documents/Clones/sefa_classroom/combinedSystem/functions/GradingInterface/gradingsystem.py", line 120, in grade
    checkfortimeout(os.system, args=[f'make test{i} >/dev/null 2>&1'])  # try to run a test
  File "/home/jack/Documents/Clones/sefa_classroom/combinedSystem/functions/GradingInterface/gradingsystem.py", line 259, in checkfortimeout
    while process1.is_alive():  # while the timeout process is still running
  File "/usr/lib/python3.9/multiprocessing/process.py", line 160, in is_alive
    assert self._parent_pid == os.getpid(), 'can only test a child process'
KeyboardInterrupt
. 