Traceback (most recent call last):
  File "runSystem.py", line 62, in <module>
    [clonedRepos, hoursLateArr] = cloneFromRepos(organization, repos, hwName, tagName, authName, authKey, profFiles, clonesRoot, f)
  File "/mnt/c/Users/leila/Documents/githubclassroom/combinedSystem/functions/cloneFromRepos.py", line 29, in cloneFromRepos
    subprocess.run(["git", "clone", "-b", tagName, str(reposURL)])
  File "/usr/lib/python3.8/subprocess.py", line 495, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1020, in communicate
    self.wait()
  File "/usr/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1806, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.8/subprocess.py", line 1764, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
